name: Cypress E2E Tests

on: workflow_dispatch

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false 
      matrix:
        containers: [1]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        if: always()
        env:
          SLACK_CHANNEL: notification-tests
          SLACK_USERNAME: qas
          SLACK_COLOR: '#1e81b0'
          MSG_MINIMAL: event,actions url
          SLACK_TITLE: 'Iniciando a execução dos tests: ' 
          SLACK_MESSAGE: ':loading_slack:'
          SLACK_FOOTER: Powered By Serverest
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npx cypress run
          spec: cypress/e2e/spec/serverest-ui.cy.js
          wait-on: 'https://serverest.dev/'
          record: true
          parallel: false 
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        if: always()
        env:
          SLACK_CHANNEL: notification-tests
          SLACK_USERNAME: qas
          SLACK_COLOR: ${{ job.status }}
          MSG_MINIMAL: event,actions url
          SLACK_TITLE: 'Resultados dos tests: ' 
          SLACK_MESSAGE: ':loading_slack:'
          SLACK_FOOTER: Powered By Serverest
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        